
make: 
	gcc -std=c99 -otictactoe.out -Isrc/ duk_src/duktape.c tictactoe.c -lm -lncurses
run:	
	gcc -std=c99 -otictactoe.out -Isrc/ duk_src/duktape.c tictactoe.c -lm -lncurses
	./tictactoe.out ${ARGS}